### PR TITLE
Add custom wrappers for js borschik tech

### PR DESCRIPTION
**Pull request by a-x-**
i need it for my task

### CODE REVIEW

**Comment by a-x-** [comment]
@blond

**Comment by tadatuta** [comment]
I'd prefer additional external tech to wrap any content as it's not something `borschik` specific.

**Comment by a-x-** [comment]
@tadatuta I had faced with enb `enb-transform-flow tech` trouble (it solves this transform problem, but it doesn't work). And don't want make new enb tech for very my own case.

Now i propose make this change as not too much linux-way deviating one.

/cc @zxqfox

**Comment by a-x-** [comment]
btw, it's that `enb-transform-flow` tech trouble https://github.com/enb/enb/pull/449

**Comment by tadatuta** [comment]
@a-x- 
>  And don't want make new enb tech for very my own case

Please use https://www.npmjs.com/package/enb-wrap

**Comment by a-x-** [comment]
thank you, @tadatuta so much!

**Pull request closed without merging**
